---
# Valence Pod Deployment Playbook
# Usage: ansible-playbook -i inventory.yml site.yml

- name: Deploy Valence Pod
  hosts: valence-pod
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: security
      tags: [security]

    - role: common
      tags: [common]

    - role: postgresql
      tags: [postgresql, db]

    - role: vkb
      tags: [vkb]

    - role: backup
      tags: [backup]

    - role: playwright
      tags: [playwright]

    - role: verify
      tags: [verify]
      when: verify_deployment | default(true)

  post_tasks:
    - name: Display connection info
      debug:
        msg: |
          Valence Pod deployed successfully!

          MCP Server: https://{{ domain }}/mcp
          Health: https://{{ domain }}/health
          PostgreSQL: localhost:5432/{{ postgres_db }}

          Next steps:
          1. Create a token: valence-token create -c my-client
          2. Add to Claude Code: claude mcp add --transport http valence https://{{ domain }}/mcp --header "Authorization: Bearer <token>"
