"""Valence Federation - Federated epistemic network for knowledge sharing.

This package implements the Valence Federation Protocol (VFP), enabling
sovereign knowledge bases to form trust networks, share intelligence,
and collectively resolve contradictions across the epistemic commons.

Key components:
- models: Data models for federation (FederationNode, FederatedBelief, NodeTrust)
- identity: DID:vkb identity system
- protocol: Federation protocol handlers
- discovery: Node discovery and registration
- sync: Belief synchronization between nodes
- trust: Trust computation and management
- privacy: Differential privacy for aggregation
- peers: In-memory peer storage (MVP)
- server: Lightweight federation server (MVP)
"""

from .models import (
    # Enums
    NodeStatus,
    TrustPhase,
    Visibility,
    ShareLevel,
    SyncStatus,
    ThreatLevel,
    ResolutionProposal,
    ResolutionStatus,
    ConsensusMethod,
    Vote,
    TrustPreference,
    AnnotationType,
    WarningSeverity,
    # Dataclasses
    FederationNode,
    FederatedBelief,
    BeliefProvenance,
    NodeTrust,
    UserNodeTrust,
    BeliefTrustAnnotation,
    AggregatedBelief,
    AggregationSource,
    TensionResolution,
    ConsensusVote,
    SyncState,
    SyncEvent,
    SyncOutboundItem,
    PrivacyParameters,
    CorroborationAttestation,
    TrustAttestation,
    AggregationQuery,
    AggregationResult,
    LocalSummary,
    TrustConcentrationWarning,
    TrustConcentrationReport,
)

from .identity import (
    DIDMethod,
    DID,
    DIDDocument,
    VerificationMethod,
    ServiceEndpoint,
    generate_keypair,
    create_web_did,
    create_key_did,
    create_user_did,
    parse_did,
    resolve_did,
)

from .protocol import (
    MessageType,
    ErrorCode,
    create_auth_challenge,
    verify_auth_challenge,
    handle_share_belief,
    handle_request_beliefs,
    handle_sync_request,
    parse_message,
    handle_message,
)

from .discovery import (
    discover_node,
    discover_node_sync,
    register_node,
    get_node_by_did,
    get_node_by_id,
    get_node_trust,
    update_node_status,
    mark_node_active,
    mark_node_unreachable,
    bootstrap_federation,
    bootstrap_federation_sync,
    check_node_health,
    check_all_nodes_health,
    list_nodes,
    list_active_nodes,
    list_nodes_with_trust,
    get_known_peers,
    exchange_peers,
)

from .sync import (
    SyncManager,
    get_sync_state,
    update_sync_state,
    queue_belief_for_sync,
    get_pending_sync_items,
    mark_sync_item_sent,
    mark_sync_item_failed,
    compare_vector_clocks,
    update_vector_clock,
    trigger_sync,
    get_sync_status,
)

from .trust import (
    TrustSignal,
    TrustManager,
    get_trust_manager,
    get_effective_trust,
    process_corroboration,
    process_dispute,
    assess_and_respond_to_threat,
    check_trust_concentration,
    SIGNAL_WEIGHTS,
    DECAY_HALF_LIFE_DAYS,
    PHASE_TRANSITION,
    THREAT_THRESHOLDS,
    PREFERENCE_MULTIPLIERS,
    CONCENTRATION_THRESHOLDS,
)

from .trust_propagation import (
    TrustPropagation,
    TrustCache,
    TransitiveTrustResult,
    TrustEdge,
    get_trust_propagation,
    compute_transitive_trust,
    invalidate_trust_cache,
    weight_query_results_by_trust,
    DEFAULT_DECAY_FACTOR,
    DEFAULT_MAX_HOPS,
    DEFAULT_CACHE_TTL,
    DEFAULT_APPLY_RING_COEFFICIENT,
)

from .ring_coefficient import (
    RingDetector,
    RingDetectionResult,
    RingCoefficientCalculator,
    TrustVelocityAnalyzer,
    TrustVelocityResult,
    SybilClusterDetector,
    SybilCluster,
    GraphAnalysisResult,
    get_ring_coefficient_calculator,
    calculate_ring_coefficient,
    record_trust_change,
    analyze_trust_graph,
    DEFAULT_RING_DAMPENING,
    MIN_RING_COEFFICIENT,
    VELOCITY_ANOMALY_THRESHOLD,
)

from .tools import (
    FEDERATION_TOOLS,
    FEDERATION_TOOL_HANDLERS,
    handle_federation_tool,
)

from .privacy import (
    # Constants
    MIN_EPSILON,
    MAX_EPSILON,
    DEFAULT_EPSILON,
    DEFAULT_DELTA,
    DEFAULT_MIN_CONTRIBUTORS,
    SENSITIVE_MIN_CONTRIBUTORS,
    HISTOGRAM_SUPPRESSION_THRESHOLD,
    MAX_QUERIES_PER_TOPIC_PER_DAY,
    MAX_QUERIES_PER_FEDERATION_PER_DAY,
    SENSITIVE_DOMAINS,
    # Enums
    PrivacyLevel,
    NoiseMechanism,
    BudgetCheckResult,
    # Config
    PrivacyConfig,
    # Budget tracking
    TopicBudget,
    RequesterBudget,
    PrivacyBudget,
    # Temporal smoothing
    MembershipEvent,
    TemporalSmoother,
    # Functions
    add_laplace_noise,
    add_gaussian_noise,
    add_noise,
    should_include_histogram,
    build_noisy_histogram,
    is_sensitive_domain,
    compute_topic_hash,
    compute_private_aggregate,
    PrivateAggregateResult,
)

from .challenges import (
    # Configuration
    ReviewerConfig,
    DEFAULT_REVIEWER_CONFIG,
    # Enums
    ChallengeType,
    ChallengeStatus,
    ReviewDecision,
    ReviewerStatus,
    # Data classes
    Challenge,
    ChallengeReview,
    ChallengeResolution,
    ReviewerReputation,
    EligibleReviewer,
    # Selection & Resolution
    ReviewerSelector,
    ChallengeResolver,
    AppealHandler,
    # Exceptions
    ChallengeError,
    InsufficientReviewersError,
    AppealNotAllowedError,
    InvalidChallengeError,
    # Validation
    validate_challenge,
)

from .aggregation import (
    # Constants
    CONFLICT_SEMANTIC_THRESHOLD,
    CONFLICT_CONFIDENCE_DIVERGENCE,
    MIN_FEDERATION_TRUST,
    DEFAULT_TRUST_WEIGHT,
    MIN_FEDERATIONS_FOR_AGGREGATE,
    # Enums
    ConflictType,
    ConflictResolution,
    AggregationStrategy,
    # Data classes
    FederationContribution,
    DetectedConflict,
    AggregationConfig,
    CrossFederationAggregateResult,
    # Classes
    ConflictDetector,
    TrustWeightedAggregator,
    PrivacyPreservingAggregator,
    FederationAggregator,
    # Functions
    aggregate_cross_federation,
    create_contribution,
)

__all__ = [
    # Enums
    "NodeStatus",
    "TrustPhase",
    "Visibility",
    "ShareLevel",
    "SyncStatus",
    "ThreatLevel",
    "ResolutionProposal",
    "ResolutionStatus",
    "ConsensusMethod",
    "Vote",
    "TrustPreference",
    "AnnotationType",
    "WarningSeverity",
    # Model dataclasses
    "FederationNode",
    "FederatedBelief",
    "BeliefProvenance",
    "NodeTrust",
    "UserNodeTrust",
    "BeliefTrustAnnotation",
    "AggregatedBelief",
    "AggregationSource",
    "TensionResolution",
    "ConsensusVote",
    "SyncState",
    "SyncEvent",
    "SyncOutboundItem",
    "PrivacyParameters",
    "CorroborationAttestation",
    "TrustAttestation",
    "AggregationQuery",
    "AggregationResult",
    "LocalSummary",
    "TrustConcentrationWarning",
    "TrustConcentrationReport",
    # Identity
    "DIDMethod",
    "DID",
    "DIDDocument",
    "VerificationMethod",
    "ServiceEndpoint",
    "generate_keypair",
    "create_web_did",
    "create_key_did",
    "create_user_did",
    "parse_did",
    "resolve_did",
    # Protocol
    "MessageType",
    "ErrorCode",
    "create_auth_challenge",
    "verify_auth_challenge",
    "handle_share_belief",
    "handle_request_beliefs",
    "handle_sync_request",
    "parse_message",
    "handle_message",
    # Discovery
    "discover_node",
    "discover_node_sync",
    "register_node",
    "get_node_by_did",
    "get_node_by_id",
    "get_node_trust",
    "update_node_status",
    "mark_node_active",
    "mark_node_unreachable",
    "bootstrap_federation",
    "bootstrap_federation_sync",
    "check_node_health",
    "check_all_nodes_health",
    "list_nodes",
    "list_active_nodes",
    "list_nodes_with_trust",
    "get_known_peers",
    "exchange_peers",
    # Sync
    "SyncManager",
    "get_sync_state",
    "update_sync_state",
    "queue_belief_for_sync",
    "get_pending_sync_items",
    "mark_sync_item_sent",
    "mark_sync_item_failed",
    "compare_vector_clocks",
    "update_vector_clock",
    "trigger_sync",
    "get_sync_status",
    # Trust
    "TrustSignal",
    "TrustManager",
    "get_trust_manager",
    "get_effective_trust",
    "process_corroboration",
    "process_dispute",
    "assess_and_respond_to_threat",
    "check_trust_concentration",
    "SIGNAL_WEIGHTS",
    "DECAY_HALF_LIFE_DAYS",
    "PHASE_TRANSITION",
    "THREAT_THRESHOLDS",
    "PREFERENCE_MULTIPLIERS",
    "CONCENTRATION_THRESHOLDS",
    # Trust Propagation
    "TrustPropagation",
    "TrustCache",
    "TransitiveTrustResult",
    "TrustEdge",
    "get_trust_propagation",
    "compute_transitive_trust",
    "invalidate_trust_cache",
    "weight_query_results_by_trust",
    "DEFAULT_DECAY_FACTOR",
    "DEFAULT_MAX_HOPS",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_APPLY_RING_COEFFICIENT",
    # Ring Coefficient
    "RingDetector",
    "RingDetectionResult",
    "RingCoefficientCalculator",
    "TrustVelocityAnalyzer",
    "TrustVelocityResult",
    "SybilClusterDetector",
    "SybilCluster",
    "GraphAnalysisResult",
    "get_ring_coefficient_calculator",
    "calculate_ring_coefficient",
    "record_trust_change",
    "analyze_trust_graph",
    "DEFAULT_RING_DAMPENING",
    "MIN_RING_COEFFICIENT",
    "VELOCITY_ANOMALY_THRESHOLD",
    # Tools
    "FEDERATION_TOOLS",
    "FEDERATION_TOOL_HANDLERS",
    "handle_federation_tool",
    # Challenges
    "ReviewerConfig",
    "DEFAULT_REVIEWER_CONFIG",
    "ChallengeType",
    "ChallengeStatus",
    "ReviewDecision",
    "ReviewerStatus",
    "Challenge",
    "ChallengeReview",
    "ChallengeResolution",
    "ReviewerReputation",
    "EligibleReviewer",
    "ReviewerSelector",
    "ChallengeResolver",
    "AppealHandler",
    "ChallengeError",
    "InsufficientReviewersError",
    "AppealNotAllowedError",
    "InvalidChallengeError",
    "validate_challenge",
    # Privacy (Issue #7 - Differential Privacy)
    "MIN_EPSILON",
    "MAX_EPSILON",
    "DEFAULT_EPSILON",
    "DEFAULT_DELTA",
    "DEFAULT_MIN_CONTRIBUTORS",
    "SENSITIVE_MIN_CONTRIBUTORS",
    "HISTOGRAM_SUPPRESSION_THRESHOLD",
    "MAX_QUERIES_PER_TOPIC_PER_DAY",
    "MAX_QUERIES_PER_FEDERATION_PER_DAY",
    "SENSITIVE_DOMAINS",
    "PrivacyLevel",
    "NoiseMechanism",
    "BudgetCheckResult",
    "PrivacyConfig",
    "TopicBudget",
    "RequesterBudget",
    "PrivacyBudget",
    "MembershipEvent",
    "TemporalSmoother",
    "add_laplace_noise",
    "add_gaussian_noise",
    "add_noise",
    "should_include_histogram",
    "build_noisy_histogram",
    "is_sensitive_domain",
    "compute_topic_hash",
    "compute_private_aggregate",
    "PrivateAggregateResult",
    # Aggregation (Issue #15 - Federation Layer with Aggregation)
    "CONFLICT_SEMANTIC_THRESHOLD",
    "CONFLICT_CONFIDENCE_DIVERGENCE",
    "MIN_FEDERATION_TRUST",
    "DEFAULT_TRUST_WEIGHT",
    "MIN_FEDERATIONS_FOR_AGGREGATE",
    "ConflictType",
    "ConflictResolution",
    "AggregationStrategy",
    "FederationContribution",
    "DetectedConflict",
    "AggregationConfig",
    "CrossFederationAggregateResult",
    "ConflictDetector",
    "TrustWeightedAggregator",
    "PrivacyPreservingAggregator",
    "FederationAggregator",
    "aggregate_cross_federation",
    "create_contribution",
]
