"""Valence Federation - Federated epistemic network for knowledge sharing.

This package implements the Valence Federation Protocol (VFP), enabling
sovereign knowledge bases to form trust networks, share intelligence,
and collectively resolve contradictions across the epistemic commons.

Key components:
- models: Data models for federation (FederationNode, FederatedBelief, NodeTrust)
- identity: DID:vkb identity system
- protocol: Federation protocol handlers
- discovery: Node discovery and registration
- sync: Belief synchronization between nodes
- trust: Trust computation and management
- privacy: Differential privacy for aggregation
- peers: In-memory peer storage (MVP)
- server: Lightweight federation server (MVP)
"""

from .aggregation import (
    CONFLICT_CONFIDENCE_DIVERGENCE,
    # Constants
    CONFLICT_SEMANTIC_THRESHOLD,
    DEFAULT_TRUST_WEIGHT,
    MIN_FEDERATION_TRUST,
    MIN_FEDERATIONS_FOR_AGGREGATE,
    AggregationConfig,
    AggregationStrategy,
    # Classes
    ConflictDetector,
    ConflictResolution,
    # Enums
    ConflictType,
    CrossFederationAggregateResult,
    DetectedConflict,
    FederationAggregator,
    # Data classes
    FederationContribution,
    PrivacyPreservingAggregator,
    TrustWeightedAggregator,
    # Functions
    aggregate_cross_federation,
    create_contribution,
)
from .challenges import (
    DEFAULT_REVIEWER_CONFIG,
    AppealHandler,
    AppealNotAllowedError,
    # Data classes
    Challenge,
    # Exceptions
    ChallengeError,
    ChallengeResolution,
    ChallengeResolver,
    ChallengeReview,
    ChallengeStatus,
    # Enums
    ChallengeType,
    EligibleReviewer,
    InsufficientReviewersError,
    InvalidChallengeError,
    ReviewDecision,
    # Configuration
    ReviewerConfig,
    ReviewerReputation,
    # Selection & Resolution
    ReviewerSelector,
    ReviewerStatus,
    # Validation
    validate_challenge,
)
from .consent import (
    ConsentChainStoreProtocol,
    ConsentValidation,
    ConsentValidationResult,
    CrossFederationConsentChain,
    # Service
    CrossFederationConsentService,
    # Data classes
    CrossFederationHop,
    # Enums (Issue #89)
    CrossFederationPolicy,
    CrossFederationRevocation,
    FederationConsentPolicy,
    # Protocols
    FederationTrustProtocol,
    GatewaySigningProtocol,
    # In-memory implementations (testing)
    InMemoryConsentChainStore,
    InMemoryPolicyStore,
    MockGatewaySigner,
    PolicyStoreProtocol,
    RevocationScope,
)
from .discovery import (
    PEER_EXCHANGE_ENDPOINT,
    PEER_EXCHANGE_MAX_PEERS,
    PEER_EXCHANGE_MIN_TRUST,
    PEER_EXCHANGE_RATE_LIMIT,
    PEER_EXCHANGE_RATE_WINDOW,
    PeerExchangeMessage,
    PeerExchangeProtocol,
    PeerExchangeResponse,
    PeerInfo,
    bootstrap_federation,
    bootstrap_federation_sync,
    check_all_nodes_health,
    check_node_health,
    discover_node,
    discover_node_sync,
    exchange_peers,
    get_known_peers,
    get_node_by_did,
    get_node_by_id,
    get_node_trust,
    get_peer_exchange_protocol,
    list_active_nodes,
    list_nodes,
    list_nodes_with_trust,
    mark_node_active,
    mark_node_unreachable,
    register_node,
    set_peer_exchange_protocol,
    update_node_status,
)
from .domain_verification import (
    CHALLENGE_PREFIX,
    # Constants
    CHALLENGE_TOKEN_LENGTH,
    CHALLENGE_TTL_HOURS,
    DNS_CHALLENGE_SUBDOMAIN,
    MIN_ATTESTATION_TRUST,
    AttestationStore,
    AttestationType,
    # Stores
    ChallengeStore,
    DefaultExternalAuthorityClient,
    DomainAttestation,
    DomainChallenge,
    # Enums (Issue #87 - Domain Verification)
    DomainVerificationMethod,
    DomainVerificationResult,
    # External authority
    ExternalAuthorityClient,
    # Data classes
    VerificationEvidence,
    check_challenge,
    check_challenge_sync,
    # Utilities
    cleanup_expired_challenges,
    # Attestation functions
    create_attestation,
    # Main functions
    create_challenge,
    # Sync wrappers
    create_challenge_sync,
    get_attestation_stats,
    get_attestation_store,
    get_challenge_stats,
    get_challenge_store,
    get_external_client,
    revoke_attestation,
    set_external_client,
    verify_domain,
    verify_domain_sync,
)
from .domain_verification import (
    ChallengeStatus as DomainChallengeStatus,
)
from .domain_verification import (
    # Batch operations
    verify_multiple_domains as verify_domains_batch,
)
from .groups import (
    AES_KEY_SIZE,
    KDF_INFO_ENCRYPTION_KEY,
    # Constants
    KDF_INFO_EPOCH_SECRET,
    KDF_INFO_MEMBER_SECRET,
    KDF_INFO_WELCOME_KEY,
    MAX_EPOCH_HISTORY,
    NONCE_SIZE,
    CommitMessage,
    EpochSecrets,
    GroupMember,
    # Enums
    GroupRole,
    GroupState,
    GroupStatus,
    # Classes
    KeyPackage,
    MemberStatus,
    RemovalAuditEntry,
    WelcomeMessage,
    add_member,
    can_decrypt_at_epoch,
    # Functions
    create_group,
    decrypt_group_content,
    encrypt_group_content,
    get_removal_history,
    process_commit,
    process_welcome,
    remove_member,
    rotate_keys,
)
from .identity import (
    DID,
    DIDDocument,
    DIDMethod,
    ServiceEndpoint,
    VerificationMethod,
    create_key_did,
    create_user_did,
    create_web_did,
    generate_keypair,
    parse_did,
    resolve_did,
)
from .models import (
    AggregatedBelief,
    AggregationQuery,
    AggregationResult,
    AggregationSource,
    AnnotationType,
    BeliefProvenance,
    BeliefTrustAnnotation,
    ConsensusMethod,
    ConsensusVote,
    CorroborationAttestation,
    FederatedBelief,
    # Dataclasses
    FederationNode,
    LocalSummary,
    # Enums
    NodeStatus,
    NodeTrust,
    PrivacyParameters,
    ResolutionProposal,
    ResolutionStatus,
    ShareLevel,
    SyncEvent,
    SyncOutboundItem,
    SyncState,
    SyncStatus,
    TensionResolution,
    ThreatLevel,
    TrustAttestation,
    TrustConcentrationReport,
    TrustConcentrationWarning,
    TrustPhase,
    TrustPreference,
    UserNodeTrust,
    Visibility,
    Vote,
    WarningSeverity,
)
from .nonces import (
    DEFAULT_NONCE_TTL_SECONDS,
    NonceTracker,
    generate_nonce,
    get_nonce_tracker,
    reset_nonce_tracker,
)
from .privacy import (
    DEFAULT_DELTA,
    DEFAULT_EPSILON,
    DEFAULT_MIN_CONTRIBUTORS,
    HISTOGRAM_SUPPRESSION_THRESHOLD,
    MAX_EPSILON,
    MAX_QUERIES_PER_FEDERATION_PER_DAY,
    MAX_QUERIES_PER_TOPIC_PER_DAY,
    # Constants
    MIN_EPSILON,
    SENSITIVE_DOMAINS,
    SENSITIVE_MIN_CONTRIBUTORS,
    BudgetCheckResult,
    # Budget storage (Issue #144 - Persist privacy budget)
    BudgetStore,
    DatabaseBudgetStore,
    FileBudgetStore,
    InMemoryBudgetStore,
    # Temporal smoothing
    MembershipEvent,
    NoiseMechanism,
    PrivacyBudget,
    # Config
    PrivacyConfig,
    # Enums
    PrivacyLevel,
    PrivateAggregateResult,
    RequesterBudget,
    TemporalSmoother,
    # Budget tracking
    TopicBudget,
    add_gaussian_noise,
    # Functions
    add_laplace_noise,
    add_noise,
    build_noisy_histogram,
    compute_private_aggregate,
    compute_topic_hash,
    is_sensitive_domain,
    should_include_histogram,
)
from .protocol import (
    ErrorCode,
    MessageType,
    create_auth_challenge,
    handle_message,
    handle_request_beliefs,
    handle_share_belief,
    handle_sync_request,
    parse_message,
    verify_auth_challenge,
)
from .ring_coefficient import (
    DEFAULT_RING_DAMPENING,
    MIN_RING_COEFFICIENT,
    VELOCITY_ANOMALY_THRESHOLD,
    GraphAnalysisResult,
    RingCoefficientCalculator,
    RingDetectionResult,
    RingDetector,
    SybilCluster,
    SybilClusterDetector,
    TrustVelocityAnalyzer,
    TrustVelocityResult,
    analyze_trust_graph,
    calculate_ring_coefficient,
    get_ring_coefficient_calculator,
    record_trust_change,
)
from .sync import (
    SyncManager,
    compare_vector_clocks,
    get_pending_sync_items,
    get_sync_state,
    get_sync_status,
    mark_sync_item_failed,
    mark_sync_item_sent,
    queue_belief_for_sync,
    trigger_sync,
    update_sync_state,
    update_vector_clock,
)
from .threat_detector import (
    THREAT_THRESHOLDS,
)
from .tools import (
    FEDERATION_TOOL_HANDLERS,
    FEDERATION_TOOLS,
    handle_federation_tool,
)
from .trust import (
    DECAY_HALF_LIFE_DAYS,
    SIGNAL_WEIGHTS,
    TrustManager,
    TrustSignal,
    assess_and_respond_to_threat,
    check_trust_concentration,
    get_effective_trust,
    get_trust_manager,
    process_corroboration,
    process_dispute,
)
from .trust_policy import (
    CONCENTRATION_THRESHOLDS,
    PHASE_TRANSITION,
    PREFERENCE_MULTIPLIERS,
)
from .trust_propagation import (
    DEFAULT_APPLY_RING_COEFFICIENT,
    DEFAULT_CACHE_TTL,
    DEFAULT_DECAY_FACTOR,
    DEFAULT_MAX_HOPS,
    TransitiveTrustResult,
    TrustCache,
    TrustEdge,
    TrustPropagation,
    compute_transitive_trust,
    get_trust_propagation,
    invalidate_trust_cache,
    weight_query_results_by_trust,
)
from .verification import (
    DEFAULT_CACHE_TTL_SECONDS,
    # Constants
    DNS_TXT_PREFIX,
    DOMAIN_CLAIM_SERVICE_TYPE,
    FAILED_VERIFICATION_TTL_SECONDS,
    DomainClaim,
    # Cache
    VerificationCache,
    # Data classes
    VerificationResult,
    VerificationStatus,
    get_verification_cache,
    get_verification_cache_stats,
    invalidate_domain_cache,
    verify_cross_federation_domain,
    verify_cross_federation_domain_sync,
    verify_did_document_claim,
    verify_did_document_claim_sync,
    # Functions
    verify_dns_txt_record,
    verify_dns_txt_record_sync,
    verify_multiple_domains,
)
from .verification import (
    # Enums
    VerificationMethod as DomainVerifyMethod,  # Renamed to avoid conflict with identity.VerificationMethod
)

__all__ = [
    # Enums
    "NodeStatus",
    "TrustPhase",
    "Visibility",
    "ShareLevel",
    "SyncStatus",
    "ThreatLevel",
    "ResolutionProposal",
    "ResolutionStatus",
    "ConsensusMethod",
    "Vote",
    "TrustPreference",
    "AnnotationType",
    "WarningSeverity",
    # Model dataclasses
    "FederationNode",
    "FederatedBelief",
    "BeliefProvenance",
    "NodeTrust",
    "UserNodeTrust",
    "BeliefTrustAnnotation",
    "AggregatedBelief",
    "AggregationSource",
    "TensionResolution",
    "ConsensusVote",
    "SyncState",
    "SyncEvent",
    "SyncOutboundItem",
    "PrivacyParameters",
    "CorroborationAttestation",
    "TrustAttestation",
    "AggregationQuery",
    "AggregationResult",
    "LocalSummary",
    "TrustConcentrationWarning",
    "TrustConcentrationReport",
    # Identity
    "DIDMethod",
    "DID",
    "DIDDocument",
    "VerificationMethod",
    "ServiceEndpoint",
    "generate_keypair",
    "create_web_did",
    "create_key_did",
    "create_user_did",
    "parse_did",
    "resolve_did",
    # Nonces (replay protection)
    "NonceTracker",
    "generate_nonce",
    "get_nonce_tracker",
    "reset_nonce_tracker",
    "DEFAULT_NONCE_TTL_SECONDS",
    # Protocol
    "MessageType",
    "ErrorCode",
    "create_auth_challenge",
    "verify_auth_challenge",
    "handle_share_belief",
    "handle_request_beliefs",
    "handle_sync_request",
    "parse_message",
    "handle_message",
    # Discovery
    "discover_node",
    "discover_node_sync",
    "register_node",
    "get_node_by_did",
    "get_node_by_id",
    "get_node_trust",
    "update_node_status",
    "mark_node_active",
    "mark_node_unreachable",
    "bootstrap_federation",
    "bootstrap_federation_sync",
    "check_node_health",
    "check_all_nodes_health",
    "list_nodes",
    "list_active_nodes",
    "list_nodes_with_trust",
    "get_known_peers",
    "exchange_peers",
    # Peer Exchange (Issue #263)
    "PeerInfo",
    "PeerExchangeMessage",
    "PeerExchangeResponse",
    "PeerExchangeProtocol",
    "get_peer_exchange_protocol",
    "set_peer_exchange_protocol",
    "PEER_EXCHANGE_MAX_PEERS",
    "PEER_EXCHANGE_RATE_LIMIT",
    "PEER_EXCHANGE_RATE_WINDOW",
    "PEER_EXCHANGE_MIN_TRUST",
    "PEER_EXCHANGE_ENDPOINT",
    # Sync
    "SyncManager",
    "get_sync_state",
    "update_sync_state",
    "queue_belief_for_sync",
    "get_pending_sync_items",
    "mark_sync_item_sent",
    "mark_sync_item_failed",
    "compare_vector_clocks",
    "update_vector_clock",
    "trigger_sync",
    "get_sync_status",
    # Trust
    "TrustSignal",
    "TrustManager",
    "get_trust_manager",
    "get_effective_trust",
    "process_corroboration",
    "process_dispute",
    "assess_and_respond_to_threat",
    "check_trust_concentration",
    "SIGNAL_WEIGHTS",
    "DECAY_HALF_LIFE_DAYS",
    "PHASE_TRANSITION",
    "THREAT_THRESHOLDS",
    "PREFERENCE_MULTIPLIERS",
    "CONCENTRATION_THRESHOLDS",
    # Trust Propagation
    "TrustPropagation",
    "TrustCache",
    "TransitiveTrustResult",
    "TrustEdge",
    "get_trust_propagation",
    "compute_transitive_trust",
    "invalidate_trust_cache",
    "weight_query_results_by_trust",
    "DEFAULT_DECAY_FACTOR",
    "DEFAULT_MAX_HOPS",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_APPLY_RING_COEFFICIENT",
    # Ring Coefficient
    "RingDetector",
    "RingDetectionResult",
    "RingCoefficientCalculator",
    "TrustVelocityAnalyzer",
    "TrustVelocityResult",
    "SybilClusterDetector",
    "SybilCluster",
    "GraphAnalysisResult",
    "get_ring_coefficient_calculator",
    "calculate_ring_coefficient",
    "record_trust_change",
    "analyze_trust_graph",
    "DEFAULT_RING_DAMPENING",
    "MIN_RING_COEFFICIENT",
    "VELOCITY_ANOMALY_THRESHOLD",
    # Tools
    "FEDERATION_TOOLS",
    "FEDERATION_TOOL_HANDLERS",
    "handle_federation_tool",
    # Challenges
    "ReviewerConfig",
    "DEFAULT_REVIEWER_CONFIG",
    "ChallengeType",
    "ChallengeStatus",
    "ReviewDecision",
    "ReviewerStatus",
    "Challenge",
    "ChallengeReview",
    "ChallengeResolution",
    "ReviewerReputation",
    "EligibleReviewer",
    "ReviewerSelector",
    "ChallengeResolver",
    "AppealHandler",
    "ChallengeError",
    "InsufficientReviewersError",
    "AppealNotAllowedError",
    "InvalidChallengeError",
    "validate_challenge",
    # Privacy (Issue #7 - Differential Privacy)
    "MIN_EPSILON",
    "MAX_EPSILON",
    "DEFAULT_EPSILON",
    "DEFAULT_DELTA",
    "DEFAULT_MIN_CONTRIBUTORS",
    "SENSITIVE_MIN_CONTRIBUTORS",
    "HISTOGRAM_SUPPRESSION_THRESHOLD",
    "MAX_QUERIES_PER_TOPIC_PER_DAY",
    "MAX_QUERIES_PER_FEDERATION_PER_DAY",
    "SENSITIVE_DOMAINS",
    "PrivacyLevel",
    "NoiseMechanism",
    "BudgetCheckResult",
    "PrivacyConfig",
    "TopicBudget",
    "RequesterBudget",
    "PrivacyBudget",
    # Budget storage (Issue #144 - Persist privacy budget)
    "BudgetStore",
    "InMemoryBudgetStore",
    "FileBudgetStore",
    "DatabaseBudgetStore",
    "MembershipEvent",
    "TemporalSmoother",
    "add_laplace_noise",
    "add_gaussian_noise",
    "add_noise",
    "should_include_histogram",
    "build_noisy_histogram",
    "is_sensitive_domain",
    "compute_topic_hash",
    "compute_private_aggregate",
    "PrivateAggregateResult",
    # Aggregation (Issue #15 - Federation Layer with Aggregation)
    "CONFLICT_SEMANTIC_THRESHOLD",
    "CONFLICT_CONFIDENCE_DIVERGENCE",
    "MIN_FEDERATION_TRUST",
    "DEFAULT_TRUST_WEIGHT",
    "MIN_FEDERATIONS_FOR_AGGREGATE",
    "ConflictType",
    "ConflictResolution",
    "AggregationStrategy",
    "FederationContribution",
    "DetectedConflict",
    "AggregationConfig",
    "CrossFederationAggregateResult",
    "ConflictDetector",
    "TrustWeightedAggregator",
    "PrivacyPreservingAggregator",
    "FederationAggregator",
    "aggregate_cross_federation",
    "create_contribution",
    # Verification (Issue #87 - Cross-Federation Domain Verification)
    "DNS_TXT_PREFIX",
    "DOMAIN_CLAIM_SERVICE_TYPE",
    "DEFAULT_CACHE_TTL_SECONDS",
    "FAILED_VERIFICATION_TTL_SECONDS",
    "DomainVerifyMethod",  # Renamed from VerificationMethod to avoid conflict
    "VerificationStatus",
    "VerificationResult",
    "DomainClaim",
    "VerificationCache",
    "verify_dns_txt_record",
    "verify_dns_txt_record_sync",
    "verify_did_document_claim",
    "verify_did_document_claim_sync",
    "verify_cross_federation_domain",
    "verify_cross_federation_domain_sync",
    "verify_multiple_domains",
    "get_verification_cache",
    "invalidate_domain_cache",
    "get_verification_cache_stats",
    # Domain Verification (Issue #87 - Enhanced domain verification)
    "DomainVerificationMethod",
    "DomainChallengeStatus",
    "AttestationType",
    "VerificationEvidence",
    "DomainVerificationResult",
    "DomainChallenge",
    "DomainAttestation",
    "ChallengeStore",
    "AttestationStore",
    "get_challenge_store",
    "get_attestation_store",
    "ExternalAuthorityClient",
    "DefaultExternalAuthorityClient",
    "get_external_client",
    "set_external_client",
    "create_challenge",
    "check_challenge",
    "verify_domain",
    "create_attestation",
    "revoke_attestation",
    "verify_domains_batch",
    "create_challenge_sync",
    "check_challenge_sync",
    "verify_domain_sync",
    "cleanup_expired_challenges",
    "get_challenge_stats",
    "get_attestation_stats",
    "CHALLENGE_TOKEN_LENGTH",
    "CHALLENGE_TTL_HOURS",
    "DNS_CHALLENGE_SUBDOMAIN",
    "CHALLENGE_PREFIX",
    "MIN_ATTESTATION_TRUST",
    # Cross-Federation Consent (Issue #89)
    "CrossFederationPolicy",
    "ConsentValidationResult",
    "RevocationScope",
    "CrossFederationHop",
    "FederationConsentPolicy",
    "CrossFederationConsentChain",
    "CrossFederationRevocation",
    "ConsentValidation",
    "FederationTrustProtocol",
    "GatewaySigningProtocol",
    "ConsentChainStoreProtocol",
    "PolicyStoreProtocol",
    "CrossFederationConsentService",
    "InMemoryConsentChainStore",
    "InMemoryPolicyStore",
    "MockGatewaySigner",
    # Groups (Issue #103 - MLS Group Management)
    "AES_KEY_SIZE",
    "KDF_INFO_ENCRYPTION_KEY",
    "KDF_INFO_EPOCH_SECRET",
    "KDF_INFO_MEMBER_SECRET",
    "KDF_INFO_WELCOME_KEY",
    "MAX_EPOCH_HISTORY",
    "NONCE_SIZE",
    "CommitMessage",
    "EpochSecrets",
    "GroupMember",
    "GroupRole",
    "GroupState",
    "GroupStatus",
    "KeyPackage",
    "MemberStatus",
    "RemovalAuditEntry",
    "WelcomeMessage",
    "add_member",
    "can_decrypt_at_epoch",
    "create_group",
    "decrypt_group_content",
    "encrypt_group_content",
    "get_removal_history",
    "process_commit",
    "process_welcome",
    "remove_member",
    "rotate_keys",
]
