"""Privacy module for Valence - share policies, encryption, and sharing service."""

from .types import ShareLevel, EnforcementType, PropagationRules, SharePolicy
from .encryption import EncryptionEnvelope
from .canary import (
    CanaryToken,
    CanaryRegistry,
    EmbeddingStrategy,
    LeakReport,
    embed_canary,
    detect_canaries,
    strip_canaries,
)
from .sharing import (
    ShareRequest,
    ShareResult,
    ConsentChainEntry,
    Share,
    SharingService,
)
from .migration import (
    migrate_visibility,
    migrate_all_beliefs,
    migrate_all_beliefs_sync,
    get_share_policy_json,
)
from .trust import (
    TrustEdge,
    TrustEdge4D,
    TrustGraphStore,
    TrustService,
    get_trust_graph_store,
    get_trust_service,
    DecayModel,
    grant_trust,
    revoke_trust,
    get_trust,
    list_trusted,
    list_trusters,
)
from .domains import (
    Domain,
    DomainMembership,
    DomainRole,
    DomainService,
    DomainError,
    DomainNotFoundError,
    DomainExistsError,
    MembershipExistsError,
    MembershipNotFoundError,
    PermissionDeniedError,
)
from .provenance import (
    ProvenanceTier,
    ProvenanceChain,
    FilteredProvenance,
    filter_provenance,
    get_tier_for_audience,
)
from .capabilities import (
    Capability,
    CapabilityAction,
    CapabilityService,
    CapabilityStore,
    InMemoryCapabilityStore,
    CapabilityError,
    CapabilityExpiredError,
    CapabilityInvalidSignatureError,
    CapabilityInvalidError,  # Alias for CapabilityInvalidSignatureError
    CapabilityRevokedError,
    CapabilityNotFoundError,
    CapabilityTTLExceededError,
    CapabilityInsufficientPermissionError,
    get_capability_service,
    set_capability_service,
    issue_capability,
    verify_capability,
    revoke_capability,
    DEFAULT_TTL_SECONDS,
    MAX_TTL_SECONDS,
)
from .audit import (
    AuditEvent,
    AuditEventType,
    AuditLog,
    AuditLogger,
    AuditBackend,
    InMemoryAuditBackend,
    FileAuditBackend,
    ChainVerificationError,
    verify_chain,
    get_audit_logger,
    set_audit_logger,
)
from .elevation import (
    ProposalStatus,
    ElevationProposal,
    ElevationError,
    ProposalNotFoundError,
    ProposalAlreadyResolvedError,
    InvalidElevationError,
    propose_elevation,
    approve_elevation,
    reject_elevation,
    create_redacted_content,
    ElevationService,
)
from .corroboration import (
    CorroborationDetector,
    CorroboratingSource,
    CorroborationEvidence,
    SimilarBelief,
    CorroborationError,
    BeliefNotFoundError,
    DuplicateSourceError,
    AutoElevationDisabledError,
    cosine_similarity,
    get_corroboration_detector,
    set_corroboration_detector,
    add_corroboration,
    get_evidence,
    propose_auto_elevation,
    opt_out_belief,
    opt_out_owner,
    DEFAULT_CORROBORATION_THRESHOLD,
    DEFAULT_SIMILARITY_THRESHOLD,
    DEFAULT_TARGET_LEVEL,
)
from .anomaly import (
    AnomalyType,
    AnomalyAlert,
    RuleConfig,
    AnomalyDetector,
    get_anomaly_detector,
    set_anomaly_detector,
)
from .reports import (
    ExportFormat,
    ReportStatus,
    ReportScope,
    BeliefRecord,
    ShareRecord,
    TrustRecord,
    AuditRecord,
    ReportMetadata,
    DataReport,
    ReportService,
    ReportStore,
    ReportDataSource,
    InMemoryReportStore,
    InMemoryDataSource,
    ReportError,
    ReportNotFoundError,
    ReportGenerationError,
    generate_data_report,
    get_report_service,
    set_report_service,
)

__all__ = [
    # Types
    "ShareLevel",
    "EnforcementType", 
    "PropagationRules",
    "SharePolicy",
    # Encryption
    "EncryptionEnvelope",
    # Canary tokens (Issue #93)
    "CanaryToken",
    "CanaryRegistry",
    "EmbeddingStrategy",
    "LeakReport",
    "embed_canary",
    "detect_canaries",
    "strip_canaries",
    # Sharing
    "ShareRequest",
    "ShareResult",
    "ConsentChainEntry",
    "Share",
    "SharingService",
    # Migration
    "migrate_visibility",
    "migrate_all_beliefs",
    "migrate_all_beliefs_sync",
    "get_share_policy_json",
    # Trust (Issue #58, #59)
    "TrustEdge",
    "TrustEdge4D",
    "TrustGraphStore",
    "TrustService",
    "get_trust_graph_store",
    "get_trust_service",
    "DecayModel",
    "grant_trust",
    "revoke_trust",
    "get_trust",
    "list_trusted",
    "list_trusters",
    # Domains
    "Domain",
    "DomainMembership",
    "DomainRole",
    "DomainService",
    "DomainError",
    "DomainNotFoundError",
    "DomainExistsError",
    "MembershipExistsError",
    "MembershipNotFoundError",
    "PermissionDeniedError",
    # Capabilities (Issue #77, #78)
    "Capability",
    "CapabilityAction",
    "CapabilityService",
    "CapabilityStore",
    "InMemoryCapabilityStore",
    "CapabilityError",
    "CapabilityExpiredError",
    "CapabilityInvalidSignatureError",
    "CapabilityInvalidError",
    "CapabilityRevokedError",
    "CapabilityNotFoundError",
    "CapabilityTTLExceededError",
    "CapabilityInsufficientPermissionError",
    "get_capability_service",
    "set_capability_service",
    "issue_capability",
    "verify_capability",
    "revoke_capability",
    "DEFAULT_TTL_SECONDS",
    "MAX_TTL_SECONDS",
    # Audit (Issue #81, #82)
    "AuditEvent",
    "AuditEventType",
    "AuditLog",
    "AuditLogger",
    "AuditBackend",
    "InMemoryAuditBackend",
    "FileAuditBackend",
    "ChainVerificationError",
    "verify_chain",
    "get_audit_logger",
    "set_audit_logger",
    # Elevation (Issue #94)
    "ProposalStatus",
    "ElevationProposal",
    "ElevationError",
    "ProposalNotFoundError",
    "ProposalAlreadyResolvedError",
    "InvalidElevationError",
    "propose_elevation",
    "approve_elevation",
    "reject_elevation",
    "create_redacted_content",
    "ElevationService",
    # Corroboration auto-elevation (Issue #96)
    "CorroborationDetector",
    "CorroboratingSource",
    "CorroborationEvidence",
    "SimilarBelief",
    "CorroborationError",
    "BeliefNotFoundError",
    "DuplicateSourceError",
    "AutoElevationDisabledError",
    "cosine_similarity",
    "get_corroboration_detector",
    "set_corroboration_detector",
    "add_corroboration",
    "get_evidence",
    "propose_auto_elevation",
    "opt_out_belief",
    "opt_out_owner",
    "DEFAULT_CORROBORATION_THRESHOLD",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "DEFAULT_TARGET_LEVEL",
    # Provenance tiers (Issue #97)
    "ProvenanceTier",
    "ProvenanceChain",
    "FilteredProvenance",
    "filter_provenance",
    "get_tier_for_audience",
    # Anomaly detection (Issue #85)
    "AnomalyType",
    "AnomalyAlert",
    "RuleConfig",
    "AnomalyDetector",
    "get_anomaly_detector",
    "set_anomaly_detector",
]
