-- Valence v2 Unified Schema
-- PostgreSQL with pgvector for similarity search
-- Fresh-install schema: reflects post-migration-023 state.
-- For upgrading existing v1 databases, apply migrations/023_v2_knowledge_system.sql

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================================================
-- KNOWLEDGE SUBSTRATE TABLES
-- ============================================================================

-- Sources: Immutable raw knowledge inputs (documents, conversations, observations, …)
CREATE TABLE IF NOT EXISTS sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    type TEXT NOT NULL,
    -- Types: document, conversation, inference, observation, api, user_input,
    --        web, code, tool_output

    title TEXT,
    url TEXT,

    -- Full text content (optional; some sources are metadata-only)
    content TEXT,

    -- Deduplication fingerprint (e.g. SHA-256 of canonical content)
    fingerprint TEXT,

    -- Reliability score — set at ingest based on source type
    -- document=0.8, code=0.8, web=0.6, conversation=0.5,
    -- observation=0.4, tool_output=0.7, user_input=0.75
    reliability NUMERIC(3,2) NOT NULL DEFAULT 0.5,

    -- For documents: content hash for deduplication
    content_hash TEXT,

    -- For conversations: link to session
    session_id UUID,  -- FK added after vkb_sessions table

    -- Flexible metadata
    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Vector embedding for semantic search (384-dim, BAAI/bge-small-en-v1.5)
    -- NULL until first retrieval need (deferred embedding, WU-12)
    embedding VECTOR(384),

    -- Full-text search over content
    content_tsv TSVECTOR
        GENERATED ALWAYS AS (to_tsvector('english', COALESCE(content, ''))) STORED
);

CREATE INDEX IF NOT EXISTS idx_sources_type ON sources(type);
CREATE INDEX IF NOT EXISTS idx_sources_hash ON sources(content_hash) WHERE content_hash IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_fingerprint ON sources(fingerprint) WHERE fingerprint IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sources_embedding
    ON sources USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 200);
CREATE INDEX IF NOT EXISTS idx_sources_tsv ON sources USING GIN (content_tsv);
CREATE INDEX IF NOT EXISTS idx_sources_created ON sources(created_at DESC);

COMMENT ON COLUMN sources.reliability IS
    'Initial reliability: document=0.8, code=0.8, web=0.6, conversation=0.5, observation=0.4, tool_output=0.7, user_input=0.75';

-- Articles: Core knowledge claims compiled from sources
CREATE TABLE IF NOT EXISTS articles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    content TEXT NOT NULL,

    -- Human-readable title (optional; auto-generated by compiler)
    title TEXT,

    -- Who authored/created this article
    author_type TEXT NOT NULL DEFAULT 'system'
        CHECK (author_type IN ('system', 'operator', 'agent')),

    -- Pinned articles are exempt from organic forgetting
    pinned BOOLEAN NOT NULL DEFAULT FALSE,

    -- Approximate token count (set on create/update)
    size_tokens INTEGER,

    -- When the article was last compiled from sources (NULL = manual / never)
    compiled_at TIMESTAMPTZ,

    -- Usage-based scoring (C4/C9 self-organisation)
    usage_score NUMERIC(8,4) NOT NULL DEFAULT 0,

    -- Dimensional confidence (JSONB for flexibility)
    -- Dimensions: overall, source_reliability, method_quality,
    -- internal_consistency, temporal_freshness, corroboration, domain_applicability
    confidence JSONB NOT NULL DEFAULT '{"overall": 0.7}',

    -- Domain classification (hierarchical path)
    domain_path TEXT[] NOT NULL DEFAULT '{}',

    -- Temporal validity
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Primary source at create-time (kept for backward compat; see article_sources for full provenance)
    source_id UUID REFERENCES sources(id) ON DELETE SET NULL,
    extraction_method TEXT,
    extraction_metadata JSONB,

    -- Supersession chain
    supersedes_id UUID REFERENCES articles(id) ON DELETE SET NULL,
    superseded_by_id UUID REFERENCES articles(id) ON DELETE SET NULL,

    -- Ownership (distinct from source provenance)
    holder_id UUID,

    -- Article versioning
    version INTEGER NOT NULL DEFAULT 1,

    -- Content integrity / deduplication
    content_hash CHAR(64),

    -- Status
    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, superseded, disputed, archived

    -- Archival tracking
    archived_at TIMESTAMPTZ,

    -- Legacy inline corroboration (kept for backward compat; prefer article_sources)
    corroboration_count INTEGER NOT NULL DEFAULT 0,
    corroborating_sources JSONB NOT NULL DEFAULT '[]',

    -- Legacy inline dimensional confidence (kept for backward compat; prefer confidence JSONB)
    confidence_source REAL DEFAULT 0.5,
    confidence_method REAL DEFAULT 0.5,
    confidence_consistency REAL DEFAULT 1.0,
    confidence_freshness REAL DEFAULT 1.0,
    confidence_corroboration REAL DEFAULT 0.1,
    confidence_applicability REAL DEFAULT 0.8,

    -- Vector embedding for similarity search (384-dim, BAAI/bge-small-en-v1.5)
    embedding VECTOR(384),

    -- Full-text search
    content_tsv TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', content)
    ) STORED,

    CONSTRAINT articles_valid_status CHECK (status IN ('active', 'superseded', 'disputed', 'archived')),
    CONSTRAINT articles_version_positive CHECK (version > 0),
    CONSTRAINT articles_valid_confidence CHECK (
        (confidence->>'overall')::numeric >= 0 AND
        (confidence->>'overall')::numeric <= 1
    )
);

CREATE INDEX IF NOT EXISTS idx_articles_domain ON articles USING GIN (domain_path);
CREATE INDEX IF NOT EXISTS idx_articles_status ON articles(status);
CREATE INDEX IF NOT EXISTS idx_articles_created ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_tsv ON articles USING GIN (content_tsv);
CREATE INDEX IF NOT EXISTS idx_articles_source ON articles(source_id);
CREATE INDEX IF NOT EXISTS idx_articles_embedding ON articles USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 200);
CREATE INDEX IF NOT EXISTS idx_articles_holder ON articles(holder_id) WHERE holder_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_articles_content_hash ON articles(content_hash) WHERE content_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_articles_archival_candidates ON articles(modified_at) WHERE status = 'superseded';
CREATE INDEX IF NOT EXISTS idx_articles_archived ON articles(archived_at DESC) WHERE status = 'archived';

-- Entities: People, organizations, tools, concepts
CREATE TABLE IF NOT EXISTS entities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name TEXT NOT NULL,
    type TEXT NOT NULL,
    -- Types: person, organization, tool, concept, project, location, service

    description TEXT,
    aliases TEXT[] DEFAULT '{}',

    -- For entity resolution (merging duplicates)
    canonical_id UUID REFERENCES entities(id) ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT entities_valid_type CHECK (type IN (
        'person', 'organization', 'tool', 'concept', 'project', 'location', 'service'
    ))
);

CREATE INDEX IF NOT EXISTS idx_entities_type ON entities(type);
CREATE INDEX IF NOT EXISTS idx_entities_name ON entities(name);
CREATE INDEX IF NOT EXISTS idx_entities_aliases ON entities USING GIN (aliases);
CREATE INDEX IF NOT EXISTS idx_entities_canonical ON entities(canonical_id) WHERE canonical_id IS NOT NULL;

-- Unique constraint on canonical entities only (case-insensitive)
CREATE UNIQUE INDEX IF NOT EXISTS idx_entities_unique_canonical
    ON entities(LOWER(name), type)
    WHERE canonical_id IS NULL;

-- Article-Entity junction (renamed from belief_entities)
CREATE TABLE IF NOT EXISTS article_entities (
    belief_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    -- NOTE: column kept as belief_id for backward compat; semantically it is article_id
    entity_id UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,

    role TEXT NOT NULL DEFAULT 'subject',
    -- Roles: subject, object, context, source

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (belief_id, entity_id, role),
    CONSTRAINT article_entities_valid_role CHECK (role IN ('subject', 'object', 'context', 'source'))
);

CREATE INDEX IF NOT EXISTS idx_article_entities_entity ON article_entities(entity_id);

-- Article Sources: Provenance — which sources contributed to which articles
CREATE TABLE IF NOT EXISTS article_sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    source_id UUID NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    relationship TEXT NOT NULL
        CHECK (relationship IN ('originates', 'confirms', 'supersedes', 'contradicts', 'contends')),
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT,
    UNIQUE(article_id, source_id, relationship)
);

CREATE INDEX IF NOT EXISTS idx_article_sources_article ON article_sources(article_id);
CREATE INDEX IF NOT EXISTS idx_article_sources_source ON article_sources(source_id);
CREATE INDEX IF NOT EXISTS idx_article_sources_rel ON article_sources(relationship);

-- Article Mutations: History of splits, merges, updates
CREATE TABLE IF NOT EXISTS article_mutations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mutation_type TEXT NOT NULL
        CHECK (mutation_type IN ('created', 'updated', 'split', 'merged', 'archived')),
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    -- For splits: the new article created from the split
    related_article_id UUID REFERENCES articles(id) ON DELETE SET NULL,
    -- For updates: the source that triggered the update
    trigger_source_id UUID REFERENCES sources(id) ON DELETE SET NULL,
    summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_article_mutations_article ON article_mutations(article_id);
CREATE INDEX IF NOT EXISTS idx_article_mutations_type ON article_mutations(mutation_type);

-- Contentions: Contradictions / disagreements between articles (renamed from tensions)
CREATE TABLE IF NOT EXISTS contentions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    belief_a_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    belief_b_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,

    type TEXT NOT NULL DEFAULT 'contradiction',
    -- Types: contradiction, temporal_conflict, scope_conflict, partial_overlap

    description TEXT,

    severity TEXT NOT NULL DEFAULT 'medium',
    -- Severity: low, medium, high, critical

    status TEXT NOT NULL DEFAULT 'detected',
    -- Status: detected, investigating, resolved, accepted

    resolution TEXT,
    resolved_at TIMESTAMPTZ,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Materiality score (importance of the contention; contentions below threshold suppressed)
    materiality NUMERIC(3,2) DEFAULT 0.5,

    -- Legacy federation columns (kept; dropped in a future cleanup migration)
    opt_out_federation BOOLEAN NOT NULL DEFAULT FALSE,
    share_policy JSONB,
    extraction_metadata JSONB,

    CONSTRAINT contentions_different_articles CHECK (belief_a_id != belief_b_id),
    CONSTRAINT contentions_valid_type CHECK (type IN (
        'contradiction', 'temporal_conflict', 'scope_conflict', 'partial_overlap'
    )),
    CONSTRAINT contentions_valid_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT contentions_valid_status CHECK (status IN ('detected', 'investigating', 'resolved', 'accepted'))
);

CREATE INDEX IF NOT EXISTS idx_contentions_status ON contentions(status);
CREATE INDEX IF NOT EXISTS idx_contentions_severity ON contentions(severity);
CREATE INDEX IF NOT EXISTS idx_contentions_belief_a ON contentions(belief_a_id);
CREATE INDEX IF NOT EXISTS idx_contentions_belief_b ON contentions(belief_b_id);

-- Mutation Queue: Deferred operations (DR-6)
CREATE TABLE IF NOT EXISTS mutation_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    operation TEXT NOT NULL
        CHECK (operation IN ('split', 'merge_candidate', 'recompile', 'decay_check', 'recompile_degraded')),
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    priority INTEGER NOT NULL DEFAULT 5,
    payload JSONB DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mutation_queue_status ON mutation_queue(status, priority);
CREATE INDEX IF NOT EXISTS idx_mutation_queue_article ON mutation_queue(article_id);

-- System Config: Bounded-memory and runtime configuration
CREATE TABLE IF NOT EXISTS system_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- CONVERSATION TRACKING TABLES (VKB)
-- Note: Uses vkb_ prefix to avoid conflicts with other tables
-- ============================================================================

-- Sessions: Meso-scale conversation tracking
CREATE TABLE IF NOT EXISTS vkb_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    platform TEXT NOT NULL,
    -- Platforms: claude-code, matrix, api, slack, openclaw, …

    project_context TEXT,

    status TEXT NOT NULL DEFAULT 'active',
    -- Status: active, completed, abandoned

    summary TEXT,
    themes TEXT[] DEFAULT '{}',

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,

    -- Claude Code session ID for resume
    claude_session_id TEXT,

    -- Room/channel reference for chat platforms
    external_room_id TEXT,

    -- Flexible metadata
    metadata JSONB DEFAULT '{}',

    -- Exchange compaction
    compacted_summary JSONB,
    compacted_at TIMESTAMPTZ,

    CONSTRAINT vkb_sessions_valid_status CHECK (status IN ('active', 'completed', 'abandoned')),
    CONSTRAINT vkb_sessions_valid_platform CHECK (platform IN (
        'claude-code', 'matrix', 'api', 'slack',
        'claude-web', 'claude-desktop', 'claude-mobile',
        'openclaw'
    ))
);

CREATE INDEX IF NOT EXISTS idx_vkb_sessions_platform ON vkb_sessions(platform);
CREATE INDEX IF NOT EXISTS idx_vkb_sessions_status ON vkb_sessions(status);
CREATE INDEX IF NOT EXISTS idx_vkb_sessions_started ON vkb_sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_vkb_sessions_project ON vkb_sessions(project_context);
CREATE INDEX IF NOT EXISTS idx_vkb_sessions_external_room ON vkb_sessions(external_room_id);
CREATE INDEX IF NOT EXISTS idx_vkb_sessions_claude_id ON vkb_sessions(claude_session_id) WHERE claude_session_id IS NOT NULL;

-- Add FK from sources to vkb_sessions (now that vkb_sessions exists)
ALTER TABLE sources
    ADD CONSTRAINT fk_sources_vkb_session
    FOREIGN KEY (session_id) REFERENCES vkb_sessions(id) ON DELETE SET NULL;

-- Exchanges: Individual conversation turns
CREATE TABLE IF NOT EXISTS vkb_exchanges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES vkb_sessions(id) ON DELETE CASCADE,

    sequence INTEGER NOT NULL,

    role TEXT NOT NULL,
    -- Roles: user, assistant, system

    content TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Approximate token count for context management
    tokens_approx INTEGER,

    -- Tools used in this turn
    tool_uses JSONB DEFAULT '[]',

    -- Vector embedding (384-dim, BAAI/bge-small-en-v1.5)
    embedding VECTOR(384),

    UNIQUE (session_id, sequence),
    CONSTRAINT vkb_exchanges_valid_role CHECK (role IN ('user', 'assistant', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_vkb_exchanges_session ON vkb_exchanges(session_id);
CREATE INDEX IF NOT EXISTS idx_vkb_exchanges_created ON vkb_exchanges(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vkb_exchanges_embedding ON vkb_exchanges USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 200);

-- Patterns: Macro-scale behavioral patterns
CREATE TABLE IF NOT EXISTS vkb_patterns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    type TEXT NOT NULL,
    -- Types: topic_recurrence, preference, working_style, communication_pattern, value_expression

    description TEXT NOT NULL,

    evidence UUID[] NOT NULL DEFAULT '{}',
    -- Array of session IDs that support this pattern

    occurrence_count INTEGER DEFAULT 1,
    confidence NUMERIC(3,2) DEFAULT 0.5,

    status TEXT NOT NULL DEFAULT 'emerging',
    -- Status: emerging, established, fading, archived

    first_observed TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_observed TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Vector embedding (384-dim, BAAI/bge-small-en-v1.5)
    embedding VECTOR(384),

    CONSTRAINT vkb_patterns_valid_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT vkb_patterns_valid_status CHECK (status IN ('emerging', 'established', 'fading', 'archived'))
);

CREATE INDEX IF NOT EXISTS idx_vkb_patterns_type ON vkb_patterns(type);
CREATE INDEX IF NOT EXISTS idx_vkb_patterns_status ON vkb_patterns(status);
CREATE INDEX IF NOT EXISTS idx_vkb_patterns_embedding ON vkb_patterns USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 200);

-- Session Insights: Links sessions to extracted articles
CREATE TABLE IF NOT EXISTS vkb_session_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES vkb_sessions(id) ON DELETE CASCADE,
    belief_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    -- NOTE: column kept as belief_id for backward compat; semantically it is article_id

    extraction_method TEXT NOT NULL DEFAULT 'manual',
    -- Methods: manual, auto, hybrid

    extracted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (session_id, belief_id),
    CONSTRAINT vkb_session_insights_valid_method CHECK (extraction_method IN ('manual', 'auto', 'hybrid'))
);

CREATE INDEX IF NOT EXISTS idx_vkb_session_insights_session ON vkb_session_insights(session_id);
CREATE INDEX IF NOT EXISTS idx_vkb_session_insights_belief ON vkb_session_insights(belief_id);

-- Article Corroborations: Deduplication and reinforcement events
CREATE TABLE IF NOT EXISTS belief_corroborations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    belief_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    -- NOTE: column kept as belief_id for backward compat; semantically it is article_id
    source_session_id UUID REFERENCES vkb_sessions(id) ON DELETE SET NULL,
    source_type TEXT NOT NULL DEFAULT 'session',
    corroborated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    similarity_score NUMERIC(4,3),
    CONSTRAINT belief_corroborations_valid_type
        CHECK (source_type IN ('session', 'user_confirm', 'federation'))
);

CREATE INDEX IF NOT EXISTS idx_belief_corroborations_belief ON belief_corroborations(belief_id);

-- Usage Traces: Article access log for feedback loop (renamed from belief_retrievals)
CREATE TABLE IF NOT EXISTS usage_traces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    belief_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    -- NOTE: column kept as belief_id for backward compat; semantically it is article_id
    query_text TEXT,
    tool_name TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    final_score NUMERIC,
    session_id UUID REFERENCES vkb_sessions(id) ON DELETE SET NULL,
    -- Source that was involved in this retrieval (optional)
    source_id UUID REFERENCES sources(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_usage_traces_belief ON usage_traces(belief_id);
CREATE INDEX IF NOT EXISTS idx_usage_traces_time ON usage_traces(retrieved_at DESC);

-- ============================================================================
-- EMBEDDING SUPPORT TABLES
-- ============================================================================

-- Embedding type registry (for multi-model support)
CREATE TABLE IF NOT EXISTS embedding_types (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    dimensions INTEGER NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT embedding_types_valid_status CHECK (status IN ('active', 'deprecated', 'backfilling'))
);

-- Only one default embedding type
CREATE UNIQUE INDEX IF NOT EXISTS idx_embedding_types_default
    ON embedding_types(is_default) WHERE is_default = TRUE;

-- Track embedding coverage across tables
CREATE TABLE IF NOT EXISTS embedding_coverage (
    content_type TEXT NOT NULL,
    content_id UUID NOT NULL,
    embedding_type_id TEXT NOT NULL REFERENCES embedding_types(id),
    embedded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (content_type, content_id, embedding_type_id)
);

CREATE INDEX IF NOT EXISTS idx_embedding_coverage_type ON embedding_coverage(embedding_type_id);

-- Tombstones: GDPR-compliant deletion tracking
CREATE TABLE IF NOT EXISTS tombstones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content_type TEXT NOT NULL,
    content_id UUID NOT NULL,
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reason TEXT NOT NULL DEFAULT 'retention_policy',
    metadata JSONB DEFAULT '{}',
    retention_until TIMESTAMPTZ,

    CONSTRAINT tombstones_valid_reason CHECK (
        reason IN ('retention_policy', 'user_request', 'gdpr_erasure', 'admin_action')
    )
);

CREATE INDEX IF NOT EXISTS idx_tombstones_content ON tombstones(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_tombstones_deleted ON tombstones(deleted_at DESC);
CREATE INDEX IF NOT EXISTS idx_tombstones_retention ON tombstones(retention_until) WHERE retention_until IS NOT NULL;

-- Consent Records: GDPR consent tracking
CREATE TABLE IF NOT EXISTS consent_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    holder_did TEXT NOT NULL,
    purpose TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT 'all',

    granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,

    -- GDPR: 7-year minimum retention
    retention_until TIMESTAMPTZ NOT NULL,

    metadata JSONB DEFAULT '{}',

    CONSTRAINT consent_records_valid_purpose CHECK (
        purpose IN ('data_processing', 'federation_sharing', 'analytics', 'backup')
    ),
    CONSTRAINT consent_records_valid_scope CHECK (
        scope IN ('all', 'beliefs', 'sessions', 'patterns')
    )
);

CREATE INDEX IF NOT EXISTS idx_consent_records_holder ON consent_records(holder_did);
CREATE INDEX IF NOT EXISTS idx_consent_records_purpose ON consent_records(holder_did, purpose);
CREATE INDEX IF NOT EXISTS idx_consent_records_active ON consent_records(holder_did)
    WHERE revoked_at IS NULL;

-- Audit Log: Append-only audit trail for all state-changing operations
CREATE TABLE IF NOT EXISTS audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actor_did TEXT,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    details JSONB DEFAULT '{}',
    ip_address TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_log_time ON audit_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log(actor_did) WHERE actor_did IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_audit_log_resource ON audit_log(resource_type, resource_id);

-- ============================================================================
-- VIEWS
-- ============================================================================

-- Current active articles (not superseded)
CREATE OR REPLACE VIEW articles_current AS
SELECT * FROM articles
WHERE status = 'active'
  AND superseded_by_id IS NULL;

-- Articles with source counts and contention flags
CREATE OR REPLACE VIEW articles_with_sources AS
SELECT
    a.*,
    COUNT(DISTINCT asrc.source_id) AS source_count,
    array_agg(DISTINCT asrc.relationship) FILTER (WHERE asrc.relationship IS NOT NULL) AS relationship_types,
    bool_or(asrc.relationship = 'contradicts' OR asrc.relationship = 'contends') AS has_contention
FROM articles a
LEFT JOIN article_sources asrc ON a.id = asrc.article_id
WHERE a.status = 'active'
GROUP BY a.id;

-- Article usage alias (belief_id column named article_id for clarity)
CREATE OR REPLACE VIEW article_usage AS
SELECT
    belief_id AS article_id,
    query_text,
    tool_name,
    retrieved_at,
    final_score,
    session_id
FROM usage_traces
WHERE belief_id IS NOT NULL;

-- Sessions with exchange and insight counts
CREATE OR REPLACE VIEW vkb_sessions_overview AS
SELECT
    s.*,
    COUNT(DISTINCT e.id) as exchange_count,
    COUNT(DISTINCT si.id) as insight_count
FROM vkb_sessions s
LEFT JOIN vkb_exchanges e ON s.id = e.session_id
LEFT JOIN vkb_session_insights si ON s.id = si.session_id
GROUP BY s.id;

-- Patterns with readable status
CREATE OR REPLACE VIEW vkb_patterns_overview AS
SELECT
    p.*,
    array_length(p.evidence, 1) as evidence_count
FROM vkb_patterns p;

-- ============================================================================
-- DEFAULT DATA
-- ============================================================================

-- Insert default embedding type (local BAAI/bge-small-en-v1.5, 384 dims)
INSERT INTO embedding_types (id, provider, model, dimensions, is_default, status)
VALUES ('local_bge_small', 'local', 'BAAI/bge-small-en-v1.5', 384, TRUE, 'active')
ON CONFLICT (id) DO NOTHING;

-- Insert default system configuration values
INSERT INTO system_config (key, value) VALUES
    ('bounded_memory',       '{"max_articles": 10000, "max_sources": 100000}'),
    ('right_sizing',         '{"max_tokens": 4000, "min_tokens": 200, "target_tokens": 2000}'),
    ('reliability_defaults', '{"document": 0.8, "code": 0.8, "web": 0.6, "conversation": 0.5, "observation": 0.4, "tool_output": 0.7, "user_input": 0.75}'),
    ('freshness',            '{"decay_rate": 0.01, "staleness_days": 90}'),
    ('contention',           '{"materiality_threshold": 0.3}')
ON CONFLICT (key) DO NOTHING;
